// export const ADD_TO_CART = "ADD_TO_CART";

// export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

// export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export const ActionTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  REMOVE_ONE: "REMOVE_ONE",
  SAVE_SHIPPING_INFO: "SAVE_SHIPPING_INFO",
};
