export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  REMOVE_ONE: "REMOVE_ONE",

  ALL_PRODUCT_REQUEST: "ALL_PRODUCT_REQUEST",
  ALL_PRODUCT_SUCCESS: "ALL_PRODUCT_SUCCESS",
  ALL_PRODUCT_FAIL: "ALL_PRODUCT_FAIL",

  NEW_PRODUCT_REQUEST: "NEW_PRODUCT_REQUEST",
  NEW_PRODUCT_SUCCESS: "NEW_PRODUCT_SUCCESS",
  NEW_PRODUCT_RESET: "NEW_PRODUCT_RESET",
  NEW_PRODUCT_FAIL: "NEW_PRODUCT_FAIL",

  UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_RESET: "UPDATE_PRODUCT_RESET",
  UPDATE_PRODUCT_FAIL: "UPDATE_PRODUCT_FAIL",

  DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_RESET: "DELETE_PRODUCT_RESET",
  DELETE_PRODUCT_FAIL: "DELETE_PRODUCT_FAIL",

  CLEAR_ERRORS: "CLEAR_ERRORS",
};
